# Generated by Django 4.2.25 on 2025-11-13 23:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_unique_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_phone', models.CharField(max_length=12)),
                ('emp_address', models.TextField(blank=True, null=True)),
                ('emp_position', models.CharField(max_length=150)),
                ('emp_password', models.CharField(max_length=255)),
                ('emp_profile', models.ImageField(blank=True, null=True, upload_to='employee_profiles/')),
                ('emp_dob', models.DateField(blank=True, null=True)),
                ('emp_qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('emp_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('work_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('work_end_time', models.TimeField(default=datetime.time(17, 0))),
                ('weekly_off_day', models.CharField(blank=True, choices=[('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('NONE', 'No Weekly Off')], help_text='Employee-specific off day (if rotational)', max_length=10, null=True)),
                ('emp_email_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HRRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('hr_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('company_password', models.CharField(max_length=200)),
                ('company_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_document', models.FileField(blank=True, null=True, upload_to='company_docs/')),
                ('company_location', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('previous_verified_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_sunday_off', models.BooleanField(default=True, help_text='If enabled, all Sundays are considered company holidays.')),
                ('weekly_off_policy', models.CharField(choices=[('SUNDAY', 'Sunday'), ('SATURDAY', 'Saturday'), ('NONE', 'No Weekly Off'), ('ROTATIONAL', 'Rotational / Employee Specific')], default='SUNDAY', help_text='Weekly off pattern for this company', max_length=15)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('email_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_day_salary', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HR_system.employee')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('total_present', models.IntegerField(default=0)),
                ('total_late', models.IntegerField(default=0)),
                ('total_late_early', models.IntegerField(default=0)),
                ('total_absent', models.IntegerField(default=0)),
                ('total_leave', models.IntegerField(default=0)),
                ('weekly_offs', models.IntegerField(default=0)),
                ('holidays', models.IntegerField(default=0)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('BANK', 'Bank Transfer'), ('UPI', 'UPI'), ('CASH', 'Cash')], max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_system.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('PAID', 'Paid Leave'), ('OTHER', 'Other')], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='leave_docs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_system.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='hr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_system.hrregister'),
        ),
        migrations.CreateModel(
            name='CompanyHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
                ('holiday_name', models.CharField(max_length=100)),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_system.hrregister')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Early Exit', 'Early Exit'), ('Late / Early Exit', 'Late / Early Exit')], default='Absent', max_length=20)),
                ('work_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('is_early_exit', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_system.employee')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
