# Generated by Django 4.2.25 on 2025-11-16 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR_system', '0002_employee_bank_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('BANK', 'Bank Transfer'), ('UPI', 'UPI'), ('CASH', 'Cash'), ('PAYU', 'PAYU')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_system.employee')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR_system.monthlypayroll')),
            ],
            options={
                'ordering': ['-paid_on'],
            },
        ),
    ]
