# Generated by Django 4.2.25 on 2025-11-16 22:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HR_system', '0003_paymenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={},
        ),
        migrations.RemoveField(
            model_name='monthlypayroll',
            name='generated_on',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='paid_on',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='per_day_salary',
        ),
        migrations.AddField(
            model_name='monthlypayroll',
            name='next_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_method',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_system.monthlypayroll'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='transaction_id',
            field=models.CharField(max_length=200),
        ),
    ]
