# Generated by Django 4.2.25 on 2025-11-16 23:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR_system', '0004_alter_paymenthistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-paid_on']},
        ),
        migrations.RemoveField(
            model_name='monthlypayroll',
            name='next_pay_date',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='net_salary',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='monthlypayroll',
            name='generated_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2025, 11, 16)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='paid_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='per_day_salary',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BANK', 'Bank Transfer'), ('UPI', 'UPI'), ('CASH', 'Cash')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_method',
            field=models.CharField(choices=[('BANK', 'Bank Transfer'), ('UPI', 'UPI'), ('CASH', 'Cash'), ('PAYU', 'PAYU')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR_system.monthlypayroll'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
