# Generated by Django 4.2.25 on 2025-11-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_system', '0005_alter_paymenthistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayroll',
            name='next_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BANK', 'Bank Transfer'), ('UPI', 'UPI'), ('CASH', 'Cash'), ('PAYU', 'PayU Gateway')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_method',
            field=models.CharField(choices=[('BANK', 'Bank Transfer'), ('UPI', 'UPI'), ('CASH', 'Cash'), ('PAYU', 'PayU Gateway')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='monthlypayroll',
            unique_together={('employee', 'month', 'year')},
        ),
    ]
