# Generated by Django 4.2.25 on 2025-11-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_system', '0006_monthlypayroll_next_pay_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayroll',
            name='is_freeze',
            field=models.BooleanField(default=False),
        ),
    ]
