# Generated by Django 4.2.25 on 2025-11-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_system', '0007_monthlypayroll_is_freeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayroll',
            name='total_early_exit',
            field=models.IntegerField(default=0),
        ),
    ]
