# Generated by Django 4.2.25 on 2025-11-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_system', '0008_monthlypayroll_total_early_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrregister',
            name='is_sunday_off',
            field=models.BooleanField(default=False, help_text='If enabled, all Sundays are considered company holidays.'),
        ),
    ]
