# Generated by Django 4.2.25 on 2025-10-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_system', '0009_alter_hrregister_is_sunday_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
